# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default=b'Just do it', max_length=64, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe5\x8d\x9a\xe5\xae\xa2\xe5\x89\xaf\xe6\xa0\x87\xe9\xa2\x98'),
        ),
    ]
