# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_blog_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ad',
            field=models.CharField(default='\u516c\u544a\u5185\u5bb9', max_length=64, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe5\x8d\x9a\xe5\xae\xa2\xe5\x85\xac\xe5\x91\x8a'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, b'Python'), (2, b'Linux\xe8\xbf\x90\xe7\xbb\xb4'), (3, b'\xe7\xbd\x91\xe7\xbb\x9c\xe5\xb7\xa5\xe7\xa8\x8b'), (4, b'\xe7\xbd\x91\xe7\xbb\x9c\xe5\xae\x89\xe5\x85\xa8')], default=None),
        ),
    ]
