# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170811_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
    ]
